"use strict";
exports.__esModule = true;
var delegate_1 = require("../lib/node/delegate");
var a = delegate_1.create(function (param) { console.log(param + " Hello"); return "Hello"; }, function (param) { console.log(param + " World "); return "world"; });
var b = delegate_1.create(function (param) { console.log(param + " Hello world"); return "Hello world"; });
var c = delegate_1.create(a, b);
a("a");
b("b");
var results = c("c");
console.log(results);
